fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener:  true
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
